# Generated by Django 5.2.5 on 2025-09-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.BigIntegerField()),
                ('accion', models.CharField(max_length=255)),
                ('tabla', models.CharField(max_length=50)),
                ('registro_id', models.BigIntegerField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditoria',
                'managed': True,
            },
        ),
    ]
